{% set name = "xscen" %}
{% set version = "0.12.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xscen-{{ version }}.tar.gz
  sha256: 13a1d9a7c608fe46a5279a393377d7007859599ba06ccc2ae116e0259cc40c09

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.10.1,<4.0
    - pip >=25.0
  run:
    - python >={{ python_min }}
    # Main package
    - cartopy >=0.23.0
    - cftime
    - cf_xarray >=0.7.6
    - clisops >=0.15.0
    - dask-core >=2024.8.1,<2024.12 # FIXME: Remove upper pin when https://github.com/pangeo-data/rechunker/pull/156 is merged
    - flox !=0.9.14
    - fsspec
    - geopandas
    - h5netcdf
    - h5py
    - intake-esm >=2023.07.07
    - matplotlib-base >=3.6
    - nc-time-axis >=1.3.1
    - netCDF4
    - numcodecs
    - numpy >=1.24
    - openpyxl
    - pandas >=2.2
    - parse
    - pyarrow >=10.0.1  # Used when opening catalogs
    - pyyaml
    - rechunker
    - scipy >=1.10
    - shapely >=2.0
    - sparse
    - toolz
    - xarray >=2023.11.0,!=2024.6.0
    - xclim >=0.55.1,<0.56
    - xesmf >=0.7,!=0.8.8
    - xsdba >=0.3.0
    - zarr >=2.13,<3


test:
  imports:
    - xscen
  source_files:
    - CHANGELOG.rst
    - docs
    - tests
    - src/xscen
  commands:
    - pip check
    - pytest tests -m "not requires_netcdf"
  requires:
    - python {{ python_min }}
    - pip
    - pytest

about:
  home: https://github.com/Ouranosinc/xscen
  summary: A climate change scenario-building analysis framework, built with xclim/xarray.
  description: |
    A climate change scenario-building analysis framework, built with Intake-esm catalogs
    and xarray-based packages such as xclim and xESMF.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://xscen.readthedocs.io
  dev_url: https://github.com/Ouranosinc/xscen

extra:
  recipe-maintainers:
    - aulemahal
    - juliettelavoie
    - RondeauG
    - Zeitsperre
