{% set name = "xscen" %}
{% set version = "0.11.0" %}
{% set python_min = python_min|default("3.10") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xscen-{{ version }}.tar.gz
  sha256: ee71f49f331456e9862556e4dbffb68d6331b6f9d434a3570623b15fd7086f5d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - babel
    - pip >=24.2.0
    - setuptools >=65.0.0
    - setuptools_scm >=8.0.0
    - wheel
  run:
    - python >={{ python_min }},<3.13
    # Main package
    - cartopy >=0.23.0
    - cftime
    - cf_xarray >=0.7.6
    - clisops >=0.10.0
    - dask-core
    - flox
    - fsspec
    - geopandas
    - h5netcdf
    - h5py
    - intake-esm >=2023.07.07
    - matplotlib-base >=3.6
    - netCDF4
    - numcodecs
    - numpy >=1.24
    - pandas >=2.2
    - parse
    - pyyaml
    - rechunker
    - scipy >=1.10
    - shapely >=2.0
    - sparse
    - toolz
    - xarray >=2023.11.0,!=2024.6.0
    - xclim >=0.53.2,<0.54
    - xesmf >=0.7
    - zarr >=2.13
    # Opt
    - nc-time-axis >=1.3.1
    - pyarrow >=10.0.1  # Used when opening catalogs

test:
  imports:
    - xscen
  source_files:
    - CHANGELOG.rst
    - docs
    - tests
  commands:
    - pip check
    - pytest tests -m "not requires_netcdf" -k "not test_common_open"
  requires:
    - python ={{ python_min }}
    - pip
    - pytest
    - xdoctest

about:
  home: https://github.com/Ouranosinc/xscen
  summary: A climate change scenario-building analysis framework, built with xclim/xarray.
  description: |
    A climate change scenario-building analysis framework, built with Intake-esm catalogs
    and xarray-based packages such as xclim and xESMF.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://xscen.readthedocs.io
  dev_url: https://github.com/Ouranosinc/xscen

extra:
  recipe-maintainers:
    - aulemahal
    - juliettelavoie
    - RondeauG
    - Zeitsperre
