{% set name = "xscen" %}
{% set version = "0.14.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xscen-{{ version }}.tar.gz
  sha256: 7b717824809b83d493a4ae4927ccf629756727eeb009b7de48621d00b1745883

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.10.1,<4.0
    - pip >=25.0
  run:
    - python >={{ python_min }}
    # Main package
    - cartopy >=0.23.0
    - cftime
    - cf_xarray >=0.7.6
    - clisops >=0.16.1
    - dask-core >=2024.8.1
    - flox
    - fsspec
    - geopandas >=1.0
    - h5netcdf >=1.5.0
    - h5py >=3.12.1
    - intake-esm ==2025.2.3
    - matplotlib-base >=3.6
    - nc-time-axis >=1.3.1
    - netCDF4
    - numcodecs <0.16.0
    - numpy >=1.24
    - openpyxl
    - pandas >=2.2
    - parse
    - pyarrow >=15.0.0
    - pydantic <2.12.0
    - pyproj
    - pyyaml
    - rechunker >=0.5.3
    - scipy >=1.11.0
    - shapely >=2.0
    - sparse
    - toolz
    - xarray >=2023.11.0,!=2024.6.0
    - xclim >=0.56.0,<0.59.0
    - xesmf >=0.7,!=0.8.8
    - xsdba >=0.4.0
    - zarr >=2.13,<3.0

test:
  imports:
    - xscen
  source_files:
    - CHANGELOG.rst
    - docs
    - tests
    - src/xscen
  commands:
    - pip check
    - pytest tests -m "not requires_netcdf"
  requires:
    - python {{ python_min }}
    - pip
    - pytest

about:
  home: https://github.com/Ouranosinc/xscen
  summary: A climate change scenario-building analysis framework, built with xclim/xarray.
  description: |
    A climate change scenario-building analysis framework, built with Intake-esm catalogs
    and xarray-based packages such as xclim and xESMF.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://xscen.readthedocs.io
  dev_url: https://github.com/Ouranosinc/xscen

extra:
  recipe-maintainers:
    - aulemahal
    - juliettelavoie
    - RondeauG
    - Zeitsperre
